### ISSUE TITLE
Price is not getting fetched

### ISSUE THREAD

**Issue by akshilshah** [tuhinpal/amazon-scraper#6]

**Comment by Dymoxz** [comment]
hi, 
i have the same problem. did you resolve yours?

**Comment by akshilshah** [comment]
@Dymoxz Hi, I have modified the scrapper and written on my own for the price.

**Comment by Dymoxz** [comment]
ah okay, could you share this with me?

**Comment by gyanexpress** [comment]
> @Dymoxz Hi, I have modified the scrapper and written on my own for the price.
> 

Can you please share the working Amazon scrapper here

**Comment by GitAjay123** [comment]
> @Dymoxz Hi, I have modified the scrapper and written on my own for the price.

can you share this with me?

**Comment by tuhinpal** [comment]
The latest version fixed these issues
